### ISSUE TITLE
[feature] 크롬 개발자 도구에서 API요청 코드 노출문제

### ISSUE THREAD

**Issue by gygy7151** [EasyAndBeauty/DailyReceipt-BE-WEB#33]
### Description
![image](https://user-images.githubusercontent.com/55748886/193862612-4829f52b-1546-4363-a809-82ef0b182d76.png)
<img width="1175" alt="image" src="https://user-images.githubusercontent.com/55748886/193863640-4e9f2c84-9e20-4d3a-b180-6c825b31f68b.png">

만약 저희팀원이 아닌 다른 누군가가 이를 악용해서
aws 과금을 엄청 물리게 할 수 있는 가능성이 있기 때문에
백엔드 서버 구축하기 전에 번들링으로 안전하게 사전 예방하는것이 중요하다고 생각합니다.
### To-Be
- 크롬 개발자 도구에서 todoController 쌩 리엑트 코드 노출되지 않게끔 번들링 되어야됨

### Todo
- [ ] 이미 설치는 되어 있으므로 어떤 모듈로부터 디펜던시를 그릴지 이미 entry 설정되어 있는지 여부체크
- [ ] 번들링 후 메인 결과물이 내보내지는 디렉토리 설정
- [ ] 만약 JS외의 리소스가 있다면 loader를 통한 필수 속성 설정

**Comment by IGhost-P** [comment]
좋은 지적입니다 블루 🦊

**Comment by gygy7151** [comment]
코멘트 고맙습니다 댄 ㅎㅎ @IGhost-P 
아 assigniees는 제가 설정하면 안되는 부분이었군요
모두다 할당 해제로 상태 다시 변경했습니다.

**Comment by java-saeng** [comment]
이 부분은 처음이라서 그러는데, 제가 처리하는걸까요?

**Comment by gygy7151** [comment]
@java-saeng  아아 프린스우 저건 '번들링'이라는 키워드와 관련된 부분이에요! 제가 프론트 이슈에 올린줄 알았는데 백엔드 레포 이슈에 잘못올렸어요 ㅎㅎ ㅠ 우가 해결하셔야 될 건 없습니댱 ~ 현재 버셀(vercel)로 배포를 해놓은 상태여서 웹팩으로 코드 번들링 작업을 다시 해야하는 부분을 언급한 거였어욥!
